version: "3"

tasks:
  run:
    desc: Run the CLI
    cmds:
      - go run cmd/cli/main.go {{.CLI_ARGS}}

  build:
    desc: Build the CLI binary
    cmds:
      - go build -o md2pw ./cmd/cli

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  release:
    desc: Release the CLI binary in local
    cmds:
      - goreleaser check
      - goreleaser release --snapshot --clean

  deploy:
    desc: Deploy the CLI on GitHub
    vars:
      TAG:
        sh: echo "{{.CLI_ARGS}}" | sed -n 's/.*--tag \([^ ]*\).*/\1/p'
    cmds:
      - |
        if [[ -z "{{.TAG}}" ]]; then
          echo "Error: --tag is required"
          exit 1
        fi
      - git tag {{.TAG}}
      - git push origin {{.TAG}}

  e2e:
    desc: Run E2E tests
    cmds:
      - cd e2e && .venv/bin/python -m pytest -v
