version: "3"

tasks:
  build:
    desc: Build the CLI binary
    cmds:
      - go build -o md2pw ./cmd/cli

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...
